[package]
name = "base58"
version = "0.1.0"
edition = "2024"

[dependencies]
seq-macro = "0.3.6"

[dev-dependencies]
hex = "0.4.3"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "encode"
harness = false
